apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  externalIPs:
  - 192.168.5.79
  ports:
  - name: mc
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: mc-udp
    port: 25565
    protocol: UDP
    targetPort: 25565
  - name: rcon
    port: 25575
    protocol: TCP
    targetPort: 25575
  - name: rcon-udp
    port: 25575
    protocol: UDP
    targetPort: 25575
  selector:
    app: minecraft-server
  sessionAffinity: None
  type: ClusterIP
